# Generated by Django 3.0.2 on 2020-06-07 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Current_Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Album name', max_length=200)),
                ('artist', models.CharField(help_text='Album artist', max_length=200)),
                ('img_url', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=4)),
                ('external_url', models.CharField(max_length=200)),
            ],
        ),
    ]
