# Generated by Django 3.0.2 on 2020-02-12 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20200211_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('post', models.TextField(help_text='What is the body of your blog post.')),
                ('pub_date', models.DateField()),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
    ]
