# Generated by Django 3.0.2 on 2020-02-12 22:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20200212_1706'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-pub_date', '-pub_time']},
        ),
        migrations.AddField(
            model_name='blogpost',
            name='pub_time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
