# Generated by Django 3.0.2 on 2020-02-25 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20200212_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='yyyy-mm-dd', null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='date_of_death',
            field=models.DateField(blank=True, help_text='yyyy-mm-dd', null=True, verbose_name='Died'),
        ),
    ]
