# Generated by Django 3.0.2 on 2020-02-25 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20200225_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='borrowed_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
