# Generated by Django 3.0.2 on 2020-05-24 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date statistics were collected.')),
                ('confirmed_cases', models.CharField(blank=True, default=None, help_text='Total number of confirmed cases in a given day.', max_length=20, null=True, verbose_name='Confirmed Cases')),
                ('total_deaths', models.CharField(blank=True, default=None, help_text='Total number of deaths.', max_length=20, null=True, verbose_name='Total Deaths')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
