# Generated by Django 3.0.2 on 2020-05-24 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0002_auto_20200524_0225'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'ordering': ['-date'], 'verbose_name_plural': 'data'},
        ),
    ]
